using System;
using System.IO;
using System.Web;
using System.Web.Caching;
using System.Web.Hosting;

/* 
 * Adapted from technique developed by Mads Kristensen
 * http://madskristensen.net/post/cache-busting-in-aspnet
 */

public class FingerPrintUrl
{
    private const string CdnUrl = "//az678787.vo.msecnd.net/cdn";

    public static string Create(string url, bool isAutoGenerated = false)
    {
        if (String.IsNullOrWhiteSpace(url))
            return String.Empty;

        if (HttpRuntime.Cache[url] == null)
        {
            string abolutePath = VirtualPathUtility.ToAbsolute("~" + url);
            string physicalPath = HostingEnvironment.MapPath(abolutePath);

            string result = url;

            if (!isAutoGenerated && File.Exists(physicalPath))
            {
                DateTime date = File.GetLastWriteTime(physicalPath);
                result += "?v=" + date.Ticks;
            }

            if (!HttpContext.Current.Request.Url.IsLoopback)
                result = result.Insert(0, CdnUrl);

            HttpRuntime.Cache.Insert(url, result, (isAutoGenerated) ? null : new CacheDependency(physicalPath));
        }

        return HttpRuntime.Cache[url] as string;
    }
}